### ISSUE TITLE
Add option to course.yml to specify minimum autohelm and minimum helm version

### ISSUE THREAD

**Issue by coreypobrien** [reactiveops/autohelm#15]
Because of certain features of helm and autohelm, sometimes a course.yml requires minimum versions of one and/or the other. It'd be nice to have that declared. Something like:

```
minimumVersions:
  helm: 2.9.0
  autohelm: 0.3.0
namespace: kube-system #namespace to install the chart in, defaults to 'kube-system'
repository: stable #repository to download chart from, defaults to 'stable'
repositories:
  incubator:
```
