### ISSUE TITLE
Git repo path failing

### ISSUE THREAD

**Issue by davekonopka** [reactiveops/autohelm#17]
I ran into in a git repo path issue running v0.3.0 with an existing `course.yml`.

```
  fluentd:
    repository:
      git: git@github.com:reactiveops/ro-charts.git
      path: fluentd-papertrail
```

The code that does the git checkout seems to put `fluentd-papertrail/fluentd` rather than `fluentd-papertrail` into the sparse checkout config. It fails out with the following error while trying to git checkout:

`stderr: 'error: Sparse checkout leaves no entry on working directory'`

I was able to get around this by changing `course.yml` to have the name match the directory. It seems like the git repo path should be independent of the chart name to allow the name to be whatever a user wants.

```
  fluentd-papertrail:
    repository:
      git: git@github.com:reactiveops/ro-charts.git
```
