### ISSUE TITLE
Values with a "." in the key are not parsed correctly

### ISSUE THREAD

**Issue by sudermanjr** [reactiveops/autohelm#24]
Consider the following snippet of a course.yml that deploys the grafana stable chart:

```
namespace: cluster-utils #namespace to install the chart in, defaults to 'kube-system'
repository: stable #repository to download chart from, defaults to 'stable'
repositories:
  incubator:
    url: https://kubernetes-charts-incubator.storage.googleapis.com
  stable:
    url: https://kubernetes-charts.storage.googleapis.com
charts: # list of charts
  grafana:
    namespace: grafana
    values:
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: prometheus-operator
            type: prometheus
            url: http://prometheus-k8s.monitoring:9090
            access: proxy
            isDefault: true
```

When deployed using autohelm, this is parsed as: 
```
datasources:
  datasources:
    yaml:
      apiVersion: 1
      datasources:
      - access: proxy
        isDefault: true
        name: prometheus-operator
        type: prometheus
        url: http://prometheus-k8s.monitoring:9090
```

However, when deployed using plain helm:
```
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: prometheus-operator
      type: prometheus
      url: http://prometheus-k8s.monitoring:9090
```

The second one is the desired behavior.  I have tried putting quotes around the key and this doesn't help.
