### ISSUE TITLE
 [feature request]: support parsing of multi-line yaml

### ISSUE THREAD

**Issue by emalloy** [reactiveops/autohelm#48]
There are cases when motivations dictate the usage of multiple line formatting for human readibility. One example would be stuffing a json snippet into the value of a key. 

It would be nice to have the ability to define key:value pairs with any of the available syntax and methods for keys over multiple lines in yaml. (block scalar and flow scalar)

Here is an example of a json value for a key `policies` that one would require when utilizing the [rabbitmq-ha](https://github.com/helm/charts/tree/master/stable/rabbitmq-ha) chart.

```yaml
policies: |-
   {
     "name": "ha-all",
     "pattern": ".*",
     "vhost": "/",
     "definition": {
       "ha-mode": "all",
       "ha-sync-mode": "automatic",
       "ha-sync-batch-size": 1
     }
   }
```

On attempting to utilize this in a `course.yaml` and executing `autohelm plot` I had experienced errors that indicated autohelm was not parsing the key as a value who contained multiple lines. If this feature is already supported, kindly inform and close out this issue. Thanks
